{
 "title": "Custom Metrics for a Python based app",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory in MB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes/1048576"
    }
   ]
  },
  {
   "title": "Total Login requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "python_login_requests_total" }
   ]
  },
  {
   "title": "Login Error Rate in Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((python_login_requests_failed_total) / (python_login_requests_failed_total + python_login_requests_processed_total) * 100)"
    }
   ]
  },
  {
   "title": "Successful Login Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "python_login_requests_processed_total"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time for Login page in Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(python_request_duration_seconds_sum)/(python_request_duration_seconds_count)*0.05"
    }
   ]
  },
  {
   "title": "Failed Login Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "python_login_requests_failed_total"
    }
   ]
  },
  {
   "title": "CPU in mI (million Instructions)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction * 1000"
    }
   ]
  },
  {
   "title": "All Login Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "python_login_requests_processed_total"
    },
    {
     "expr": "python_login_requests_failed_total"
    },
    { "expr": "python_login_requests_total" }
   ]
  },
  {
   "title": "Throughput (Login Request per Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(python_login_requests_total[30s])"
    }
   ]
  },
  {
   "title": "Average Response Time for Login Page in Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(python_request_duration_seconds_sum)/(python_request_duration_seconds_count)"
    }
   ]
  }
 ]
}